CREATE TABLE `dadosTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`importacaoId` int NOT NULL,
	`atendimento` varchar(50) NOT NULL,
	`nrInternoConta` varchar(50),
	`sequencia` varchar(50),
	`dataFaturado` timestamp,
	`guia` varchar(100),
	`convenio` varchar(255),
	`paciente` varchar(255),
	`dataConta` timestamp,
	`codigo` varchar(50),
	`codigoConvenio` varchar(50),
	`descricao` text,
	`quantidade` decimal(10,4),
	`unidade` varchar(20),
	`valorUnitario` decimal(12,4),
	`valorTotal` decimal(12,4),
	`setor` varchar(255),
	`protocolo` varchar(100),
	`statusProtocolo` varchar(50),
	`tipo` enum('MATERIAL','HONORARIO') NOT NULL,
	`medico` varchar(255),
	`funcaoMedico` varchar(100),
	`crm` varchar(50),
	`valorMedico` decimal(12,4),
	`processado` enum('sim','nao') NOT NULL DEFAULT 'nao',
	`procedimentoId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dadosTasy_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `importacoesTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`userId` int NOT NULL,
	`nomeArquivo` varchar(255) NOT NULL,
	`tamanhoArquivo` int,
	`totalRegistros` int DEFAULT 0,
	`registrosImportados` int DEFAULT 0,
	`registrosIgnorados` int DEFAULT 0,
	`registrosErro` int DEFAULT 0,
	`totalMateriais` int DEFAULT 0,
	`totalHonorarios` int DEFAULT 0,
	`dataInicio` timestamp,
	`dataFim` timestamp,
	`status` enum('aguardando','processando','concluido','concluido_parcial','erro') NOT NULL DEFAULT 'aguardando',
	`progresso` int DEFAULT 0,
	`mensagemErro` text,
	`logProcessamento` json,
	`s3Key` varchar(512),
	`s3Url` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `importacoesTasy_id` PRIMARY KEY(`id`)
);
