CREATE TABLE `faturamento_tiss` (
	`id` int AUTO_INCREMENT NOT NULL,
	`numero_lote` varchar(20),
	`sequencial_transacao` varchar(20),
	`data_registro` timestamp,
	`registro_ans` varchar(10),
	`numero_guia_prestador` varchar(20),
	`numero_guia_operadora` varchar(20),
	`senha` varchar(20),
	`carteira_beneficiario` varchar(20),
	`tipo_item` varchar(20),
	`sequencial_item` int,
	`data_execucao` timestamp,
	`codigo_tabela` varchar(5),
	`codigo_item` varchar(20),
	`descricao_item` varchar(255),
	`quantidade` decimal(10,3),
	`valor_unitario` decimal(12,2),
	`valor_total_item` decimal(12,2),
	`nome_prof` varchar(150),
	`conselho_prof` varchar(20),
	`valor_total_geral_guia` decimal(12,2),
	`estabelecimento_id` int,
	`arquivo_id` int,
	`data_importacao` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `faturamento_tiss_id` PRIMARY KEY(`id`)
);
