CREATE TABLE `recebimentos_excel` (
	`id` int AUTO_INCREMENT NOT NULL,
	`arquivo_id` int,
	`data_pagto` timestamp,
	`processado` decimal(12,2),
	`protocolo_tiss` varchar(50),
	`lote_prestador` varchar(50),
	`codigo_prestador_pagamento` varchar(50),
	`nome_prestador_pagamento` varchar(255),
	`numero_guia` varchar(50),
	`seq` int,
	`beneficiario` varchar(50),
	`nome_beneficiario` varchar(255),
	`data_execucao` timestamp,
	`hora_execucao` varchar(20),
	`item` varchar(50),
	`item_desc` varchar(500),
	`quantidade` int,
	`valor_pagamento` decimal(12,2),
	`tipo_lancamento` varchar(100),
	`erro_tiss` varchar(50),
	`situacao_item` varchar(50),
	`codigo_solicitante` varchar(50),
	`nome_solicitante` varchar(255),
	`acomodacao_internacao` varchar(100),
	`data_inicio_faturamento_internacao` timestamp,
	`data_fim_faturamento_internacao` timestamp,
	`codigo_prestador` varchar(50),
	`nome_prestador` varchar(255),
	`prestador_executante` varchar(50),
	`nome_prestador_executante` varchar(255),
	`data_importacao` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `recebimentos_excel_id` PRIMARY KEY(`id`)
);
